BEGIN;

ALTER TABLE "DispatchEventOutbox"
  DROP CONSTRAINT "DispatchEventOutbox_type_check";

ALTER TABLE "DispatchEventOutbox"
  ADD CONSTRAINT "DispatchEventOutbox_type_check" CHECK (
    "type" IN (
      'ORDER_CREATED',
      'ORDER_UPDATED',
      'ORDER_CANCELLED',
      'DRIVER_LOCATION_UPDATED',
      'DRIVER_SHIFT_STARTED',
      'DRIVER_SHIFT_ENDED',
      'DRIVER_AVAILABILITY_CHANGED',
      'ASSIGNMENT_ASSIGNED',
      'ASSIGNMENT_REASSIGNED',
      'ASSIGNMENT_WITHDRAWN',
      'ASSIGNMENT_CANCELLED',
      'ASSIGNMENT_UNLOCKED',
      'BASELINE_RECALCULATION',
      'DEPART',
      'ARRIVE',
      'COMPLETE',
      'MODULE_CHANGE_APPLIED'
    )
  );

COMMIT;
